### ISSUE TITLE
xref: `NetlinkDeserializable`

### ISSUE THREAD

**Issue by stappersg** [rust-netlink/netlink-proto#15]
A cross reference to https://github.com/rust-netlink/genetlink/issues/7 which is about
```text
error[E0277]: the trait bound `RawGenlMessage: netlink_packet_core::traits::NetlinkDeserializable` is not satisfied
  --> src/connection.rs:41:5
   |
41 |     Connection<RawGenlMessage, S>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `netlink_packet_core::traits::NetlinkDeserializable` is not implemented for `RawGenlMessage`
   |
note: required by a bound in `Connection`
  --> /home/stappers/.cargo/registry/src/index.crates.io-6f17d22bba15001f/netlink-proto-0.11.2/src/connection.rs:38:38
   |
38 |     T: Debug + NetlinkSerializable + NetlinkDeserializable,
   |                                      ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Connection`
```

**Comment by stappersg** [comment]
Screenshot of a _git bisect_
```text
stappers@juli:~/src/rust/netlink-proto
$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 1 step)
[fb0bc8f7ca2618de1539969c1d4adb1ef10f5ee7] New release 0.11.2
stappers@juli:~/src/rust/netlink-proto
$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[7e6685c9906a8c301c2da046f9f60bbdb41c1a1b] Use netlink-packet-core 0.7.0
stappers@juli:~/src/rust/netlink-proto
$ git bisect bad
7e6685c9906a8c301c2da046f9f60bbdb41c1a1b is the first bad commit
commit 7e6685c9906a8c301c2da046f9f60bbdb41c1a1b
Author: Gris Ge <fge@redhat.com>
Date:   Sun Jul 9 15:42:53 2023 +0800

    Use netlink-packet-core 0.7.0
    
    Signed-off-by: Gris Ge <fge@redhat.com>

 Cargo.toml        |  2 +-
 src/connection.rs | 18 +++++++++++++++---
 2 files changed, 16 insertions(+), 4 deletions(-)
stappers@juli:~/src/rust/netlink-proto
$ 
```
And that is what #16 is probably about.

**Comment by stappersg** [comment]
Link to commit 7e6685c9906a8c (the commit that I found with _git bisect_)

**Comment by stappersg** [comment]
Closing this _cross reference issue_ because the [original issue](https://github.com/rust-netlink/genetlink/issues/7) is fixed.
